Feat/product swap
FriederikeM/routinely pull request #48
Opened 2021-05-18 19:41 UTC by FriederikeM

* Let user swap conflicting products 
* Don't let user add conflicting together anymore

2021-05-18 20:46 UTC, hugh-burgess requested changes
Great PR for the lads. Lgtmtmttgm

2021-05-18 20:46 UTC, hugh-burgess commented on src/components/FormModal/AlertModal.js
> +  onProductSwapClicked,
Incredible renaming

2021-05-18 20:46 UTC, hugh-burgess commented on src/components/FormModal/AlertModal.js
> -          add anyway
Class name “add anyway”? Come on let’s have a more specific one

2021-05-18 20:46 UTC, hugh-burgess commented on src/components/FormModal/FormModal.js
> +    } else if (isNothingChecked === true && editMode === true) {
Couldn’t these just be `if`?

2021-05-18 20:46 UTC, hugh-burgess commented on src/utility/findConflictingProduct.js
> +export function findConflictingProductId(
Incredible effort today

2021-05-18 20:46 UTC, hugh-burgess commented on src/utility/localStorage.js
> +export default function removeProductFromLocalStorage(bla) {
Hahaha “bla”. Think about future Rikki

2021-05-18 20:51 UTC, FriederikeM commented on src/utility/localStorage.js
> +export default function removeProductFromLocalStorage(bla) {
woops... 🙈

2021-05-19 08:02 UTC, soerendolling approved these changes
looks all fine to me

2021-05-19 10:16 UTC, marwinburesch requested changes
I think you've increased readability, excellent! 🐜 
Good, risky call on this feature. It's done 🎉 

`src/components/FormModal/Form.css` doesn't have to be in this PR :)

2021-05-19 10:16 UTC, marwinburesch commented on src/components/FormModal/AlertModal.css
> +  filter: none important!;
It is used a little differently, if at all :) 
https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#the_!important_exception

2021-05-19 10:16 UTC, marwinburesch commented on src/components/FormModal/AlertModal.css
> +  height: auto;
Should be default

2021-05-19 10:16 UTC, marwinburesch commented on src/components/FormModal/AlertModal.css
> +  width: 80vw;
I think you're overwriting this with a media query, which doesn't do much (I think). You could just use the `left` and `right` properties to assign a width. Or leave it at 80% always 🤷

2021-05-19 10:16 UTC, marwinburesch commented on src/components/FormModal/AlertModal.css
> +    position: absolute;
Isn't it fixed?

2021-05-19 10:16 UTC, marwinburesch commented on src/components/FormModal/AlertModal.css
> +  height: 40px;
🤔

2021-05-19 10:32 UTC, merged